#!/usr/bin/env bash
# Phase 2. Phase 1 established that six different causes all produce an
# identical bare "419 Page Expired", which is why the usual checklist advice
# cannot be acted on: nothing in the response tells you which one you have.
#
# This installs a diagnostic that classifies the cause at the moment the
# exception is thrown, then replays all six scenarios to check the
# classification is actually correct rather than merely plausible.
set -uo pipefail

APP=/lab/app419
BASE=http://127.0.0.1:8000
cd "$APP"

# ------------------------------------------------------------ diagnostic ----
# Both files live in the repo rather than being generated by a heredoc, so a
# reader can copy them into a real application unchanged.
mkdir -p app/Support app/Http/Middleware
cp /lab/CsrfDiagnosis.php app/Support/CsrfDiagnosis.php
cp /lab/DiagnoseCsrf.php app/Http/Middleware/DiagnoseCsrf.php
php -l app/Support/CsrfDiagnosis.php
php -l app/Http/Middleware/DiagnoseCsrf.php
php /lab/install-diagnosis.php bootstrap/app.php
php -l bootstrap/app.php

start_server() {
  php artisan config:clear >/dev/null 2>&1
  php artisan route:clear >/dev/null 2>&1
  php artisan serve --host=127.0.0.1 --port=8000 >/tmp/serve.log 2>&1 &
  SERVER_PID=$!
  for _ in $(seq 1 40); do curl -s -o /dev/null "$BASE/form" && return 0; sleep 0.25; done
  echo "server failed to start"; cat /tmp/serve.log; exit 1
}
stop_server() {
  [ -n "${SERVER_PID:-}" ] && kill "$SERVER_PID" 2>/dev/null
  pkill -f 'artisan serve' 2>/dev/null
  pkill -f 'php -S 127.0.0.1:8000' 2>/dev/null
  for _ in $(seq 1 40); do curl -s -o /dev/null --max-time 1 "$BASE/form" || return 0; sleep 0.25; done
  echo "  !! port still answering"
}
get_token() {
  rm -f "$1"
  curl -s -c "$1" "$BASE/form" | grep -o 'name="_token" value="[^"]*"' | sed 's/.*value="//;s/"//'
}
show() { printf '  %-28s %s' "$1" "$2"; }

start_server
echo
echo "############ replaying each cause against the diagnostic ############"
echo

echo "B. form without @csrf"
rm -f /tmp/d1; curl -s -c /tmp/d1 -o /dev/null "$BASE/form"
show "expect NO_TOKEN_SUBMITTED" "$(curl -s -b /tmp/d1 -X POST "$BASE/form" -d 'payload=x')"

echo "D. token sent, cookie withheld"
T=$(get_token /tmp/d2)
show "expect NO_SESSION_COOKIE" "$(curl -s -X POST "$BASE/form" -d "_token=$T" -d 'payload=x')"

echo "E. token from another session"
T1=$(get_token /tmp/d3a); T2=$(get_token /tmp/d3b)
show "expect TOKEN_MISMATCH" "$(curl -s -b /tmp/d3b -X POST "$BASE/form" -d "_token=$T1" -d 'payload=x')"

echo "F. APP_KEY rotated after the form was served"
T=$(get_token /tmp/d4)
stop_server
OLD_KEY=$(grep '^APP_KEY=' .env)
php artisan key:generate --force --quiet
start_server
show "expect COOKIE_UNDECRYPTABLE" "$(curl -s -b /tmp/d4 -X POST "$BASE/form" -d "_token=$T" -d 'payload=x')"
stop_server
sed -i "s|^APP_KEY=.*|$OLD_KEY|" .env

echo "G. session expired server-side"
sed -i 's/^SESSION_LIFETIME=.*/SESSION_LIFETIME=1/' .env
start_server
T=$(get_token /tmp/d5)
find storage/framework/sessions -type f -exec touch -d '10 minutes ago' {} \;
show "expect SESSION_GONE" "$(curl -s -b /tmp/d5 -X POST "$BASE/form" -d "_token=$T" -d 'payload=x')"
stop_server
sed -i 's/^SESSION_LIFETIME=.*/SESSION_LIFETIME=120/' .env

echo
echo "A. control — a correct submission must still succeed"
start_server
T=$(get_token /tmp/d6)
printf '  %-28s %s\n' "expect ACCEPTED" \
  "$(curl -s -b /tmp/d6 -c /tmp/d6 -X POST "$BASE/form" -d "_token=$T" -d 'payload=x')"
stop_server

echo
echo "=== done ==="
